export type FAQCategory =
  | "General"
  | "Tourist"
  | "Business"
  | "Student"
  | "Work"
  | "Family"
  | "Documentation"
  | "Interviews"
  | "Refusals"
  | "Readiness";

export type FAQItem = {
  id: string;
  question: string;
  answer: string;
  category: FAQCategory;
  relatedCountrySlugs?: string[];
  relatedServiceSlugs?: string[];
  relatedGuideSlugs?: string[];
};

export const faqsData: FAQItem[] = [
  {
    id: "gen-1",
    question: "Does Visaworx guarantee visa approval or embassy decision timelines?",
    answer: "No. Visa decisions and processing times are controlled solely by government and consular authorities. Visaworx provides information, document review, and preparation guidance.",
    category: "General",
    relatedGuideSlugs: ["how-to-check-current-official-visa-requirements"],
  },
  {
    id: "gen-2",
    question: "How is Visaworx different from a typical visa processing agency?",
    answer: "Visaworx focuses on visa intelligence and preparation before application. We evaluate readiness, identify document gaps, and provide access to human experts rather than functioning as a high-volume filing proxy.",
    category: "General",
  },
  {
    id: "tour-1",
    question: "How many months of bank statements are required for a tourist visa?",
    answer: "Most consulates require 3 to 6 consecutive months of personal bank statements showing regular income credits and genuine personal savings sufficient for your intended stay.",
    category: "Tourist",
    relatedServiceSlugs: ["tourist-visa"],
    relatedGuideSlugs: ["how-to-prepare-financial-evidence"],
  },
  {
    id: "bus-1",
    question: "Can I perform paid work for a local employer on a Business Visitor visa?",
    answer: "No. Business visitor visas strictly prohibit gainful local employment. They are limited to non-paid professional activities such as attending meetings, trade shows, or contract negotiations.",
    category: "Business",
    relatedServiceSlugs: ["business-visa"],
    relatedGuideSlugs: ["business-visa-document-preparation"],
  },
  {
    id: "stu-1",
    question: "What financial proof is accepted for student visa applications?",
    answer: "Consulates generally accept liquid bank balances, official education loan sanction letters, government or university scholarships, and fixed deposits owned by immediate family sponsors.",
    category: "Student",
    relatedServiceSlugs: ["student-visa"],
    relatedGuideSlugs: ["how-to-prepare-student-visa-documents"],
  },
  {
    id: "work-1",
    question: "Does Visaworx offer job recruitment or work permit sponsorship services?",
    answer: "No. Visaworx does not recruit or provide job placement. We assist professionals holding valid job offers in compiling and verifying employer-backed visa documents.",
    category: "Work",
    relatedServiceSlugs: ["work-visa"],
  },
  {
    id: "fam-1",
    question: "Do relationship certificates require official translations?",
    answer: "Yes. Civil certificates (marriage, birth) issued in regional languages generally require certified English translations that conform to consular submission standards.",
    category: "Family",
    relatedServiceSlugs: ["family-dependent-visa"],
    relatedGuideSlugs: ["family-visit-visa-preparation"],
  },
  {
    id: "doc-1",
    question: "What happens if there is a name mismatch between my passport and supporting documents?",
    answer: "Name mismatches frequently trigger consular queries. You should obtain an official name correction, submit an official affidavit, or ensure official gazette notifications are attached.",
    category: "Documentation",
    relatedServiceSlugs: ["documentation-review"],
    relatedGuideSlugs: ["common-visa-application-mistakes"],
  },
  {
    id: "int-1",
    question: "How should I answer questions during a US visa consular interview?",
    answer: "Answer questions concisely, directly, and truthfully in your own words. Never recite memorized scripts or volunteer unsolicited information.",
    category: "Interviews",
    relatedServiceSlugs: ["interview-preparation"],
    relatedGuideSlugs: ["visa-interview-preparation-guide"],
  },
  {
    id: "ref-1",
    question: "Should I re-apply immediately after a visa refusal?",
    answer: "Rushing to re-apply without changed circumstances or missing evidence usually results in a second refusal. Evaluate refusal grounds objectively and address document gaps first.",
    category: "Refusals",
    relatedServiceSlugs: ["refusal-review"],
    relatedGuideSlugs: ["understanding-visa-refusal-reasons", "when-to-consider-reapplying-after-refusal"],
  },
  {
    id: "read-1",
    question: "Does a 'Good Foundation' readiness result mean my visa is guaranteed?",
    answer: "No. 'Good Foundation' indicates that your document assembly aligns well with typical requirements. Final decisions rest solely with government consular officers.",
    category: "Readiness",
    relatedServiceSlugs: ["visa-readiness-review"],
    relatedGuideSlugs: ["visa-readiness-before-you-apply"],
  },
  {
    id: "schengen-in-1",
    question: "What documents are required for a Schengen visa from India?",
    answer: "Consulates in India generally ask for a passport issued within the last ten years with at least two blank pages, a completed application form, travel medical insurance covering all Schengen states, proof of accommodation and travel, and financial evidence such as stamped bank statements, payslips and income tax records. The exact list is published by the consulate deciding your application, so check that mission's own checklist.",
    category: "Documentation",
    relatedCountrySlugs: ["schengen"],
    relatedServiceSlugs: ["documentation-review", "tourist-visa"],
    relatedGuideSlugs: ["schengen-visa-from-india"],
  },
  {
    id: "schengen-in-2",
    question: "How long does a Schengen visa take to process?",
    answer: "Under the EU Visa Code an application should be decided within 15 calendar days of being lodged. That period can be extended to 45 days where a case needs closer examination or further documents. The clock starts when the application is lodged, not when you book the appointment, so appointment waiting time sits on top of it.",
    category: "Tourist",
    relatedCountrySlugs: ["schengen"],
    relatedGuideSlugs: ["schengen-visa-from-india"],
  },
  {
    id: "schengen-in-3",
    question: "How early can I apply for a Schengen visa?",
    answer: "You may lodge a short-stay application up to six months before your intended travel date. Consulates advise applying no later than 15 calendar days before departure. Applying early is usually the single cheapest way to protect a trip, because it leaves room for an extended examination without threatening your travel dates.",
    category: "Tourist",
    relatedCountrySlugs: ["schengen"],
    relatedGuideSlugs: ["schengen-visa-from-india"],
  },
  {
    id: "schengen-in-4",
    question: "Do Indian passport holders need ETIAS?",
    answer: "No. ETIAS is a travel authorisation for nationals who can enter the Schengen Area without a visa. Indian passport holders require a Schengen visa, so ETIAS does not apply to them. ETIAS is also not yet in operation. If you hold a valid Schengen visa, that visa is your authorisation to travel.",
    category: "General",
    relatedCountrySlugs: ["schengen"],
    relatedGuideSlugs: ["schengen-visa-from-india"],
  },
  {
    id: "schengen-in-5",
    question: "Which Schengen country should I apply to for a multi-country trip?",
    answer: "Apply to the country that is your main destination, judged by the length and purpose of your stay. Where you are spending equal time in more than one country, apply to the country you will enter first. This is a rule, not a preference, and applying to the wrong consulate is a common cause of delay.",
    category: "Tourist",
    relatedCountrySlugs: ["schengen"],
    relatedServiceSlugs: ["tourist-visa"],
    relatedGuideSlugs: ["schengen-visa-from-india"],
  },
  {
    id: "schengen-in-6",
    question: "How much travel insurance do I need for a Schengen visa?",
    answer: "Travel medical insurance must cover a minimum of EUR 30,000 in medical expenses, be valid in every Schengen state, and cover the full duration of your stay. Cover that stops before your return date, or that names only one country, is a frequent reason for a file being treated as incomplete.",
    category: "Documentation",
    relatedCountrySlugs: ["schengen"],
    relatedServiceSlugs: ["documentation-review"],
    relatedGuideSlugs: ["schengen-visa-from-india"],
  },
  {
    id: "uk-in-1",
    question: "Do Indian nationals need a UK visa, or is an ETA enough?",
    answer: "Indian nationals need a Standard Visitor visa. The UK Electronic Travel Authorisation is only open to nationalities on the ETA national list, and India is not on it. GOV.UK states that other nationalities cannot get an ETA and should check whether they need a visa instead. Applying for an ETA from India wastes time you will need for the visa.",
    category: "Tourist",
    relatedCountrySlugs: ["united-kingdom"],
    relatedGuideSlugs: ["uk-visitor-visa-from-india"],
  },
  {
    id: "uk-in-2",
    question: "How much does a UK Standard Visitor visa cost?",
    answer: "A Standard Visitor visa costs GBP 135 for a visa of up to six months. Longer-validity visitor visas cost more, and separate charges apply for optional priority services and for the visa application centre. Confirm the current fee on GOV.UK before you pay, as visitor fees are reviewed periodically.",
    category: "Tourist",
    relatedCountrySlugs: ["united-kingdom"],
    relatedGuideSlugs: ["uk-visitor-visa-from-india"],
  },
  {
    id: "uk-in-3",
    question: "How early can I apply for a UK visitor visa?",
    answer: "The earliest you can apply is three months before you travel. That is a narrower window than the Schengen six months, so if you are planning a trip covering both the UK and Europe you cannot apply for them on the same timetable. Appointment availability at the visa application centre sits on top of processing time.",
    category: "Tourist",
    relatedCountrySlugs: ["united-kingdom"],
    relatedGuideSlugs: ["uk-visitor-visa-from-india"],
  },
  {
    id: "uk-in-4",
    question: "How long can I stay in the UK on a visitor visa?",
    answer: "You can usually stay for up to six months per visit. Extension is possible only in limited circumstances, such as continuing medical treatment. The six months is a maximum rather than an entitlement, and the length of stay you request should match the purpose your documents describe.",
    category: "Tourist",
    relatedCountrySlugs: ["united-kingdom"],
    relatedGuideSlugs: ["uk-visitor-visa-from-india"],
  },
  {
    id: "uk-in-5",
    question: "Can I work or study on a UK Standard Visitor visa?",
    answer: "You cannot do paid or unpaid work for a UK company or as a self-employed person, unless it falls under a permitted paid engagement. Some study is allowed, including recreational courses of up to 30 days. You also cannot claim public funds, marry or register a civil partnership, or live in the UK through frequent successive visits.",
    category: "Tourist",
    relatedCountrySlugs: ["united-kingdom"],
    relatedGuideSlugs: ["uk-visitor-visa-from-india"],
  },
  {
    id: "uk-in-6",
    question: "Does a previous visa refusal affect a UK visitor application?",
    answer: "A previous refusal does not bar you from applying, and refusals from other countries are relevant too. What causes real difficulty is failing to disclose one. Non-disclosure is treated far more seriously than the original refusal, because it goes to the credibility of everything else in your application. Declare it and address what has changed since.",
    category: "Refusals",
    relatedCountrySlugs: ["united-kingdom"],
    relatedServiceSlugs: ["refusal-review"],
    relatedGuideSlugs: ["uk-visitor-visa-from-india", "understanding-visa-refusal-reasons"],
  },
  {
    id: "uae-in-1",
    question: "Do Indian passport holders get a UAE visa on arrival?",
    answer: "Only conditionally. An Indian ordinary passport alone does not qualify you. You also need a valid visa, residence permit or Green Card from the United States, the United Kingdom or the European Union, or since 13 February 2025 a valid residence permit from Australia, Canada, Japan, New Zealand, the Republic of Korea or Singapore. Without one of those, you need an entry permit arranged before you travel.",
    category: "Tourist",
    relatedCountrySlugs: ["united-arab-emirates"],
    relatedGuideSlugs: ["uae-visa-from-india"],
  },
  {
    id: "uae-in-2",
    question: "How long is the UAE visa on arrival valid for Indian nationals?",
    answer: "It is a visitor entry of 14 days, extendable once for a similar period. The extension is available one time only, so if your trip is planned around a longer stay this route will not accommodate it even if you qualify. Plan the length of the trip around the permission, not the other way round.",
    category: "Tourist",
    relatedCountrySlugs: ["united-arab-emirates"],
    relatedGuideSlugs: ["uae-visa-from-india"],
  },
  {
    id: "uae-in-3",
    question: "How much validity do my documents need for a UAE visa on arrival?",
    answer: "Both your passport and the qualifying document need at least six months validity. A US visa or UK residence permit with four months remaining does not qualify you, even though it remains valid for its own country. Travellers commonly check the passport and forget the second document.",
    category: "Documentation",
    relatedCountrySlugs: ["united-arab-emirates"],
    relatedGuideSlugs: ["uae-visa-from-india"],
  },
  {
    id: "uae-in-4",
    question: "What if I do not qualify for a UAE visa on arrival?",
    answer: "You arrange an entry permit before travelling, applied for through a sponsor rather than by you directly. That sponsor is usually an airline, hotel, licensed tour operator, or a relative or company resident in the UAE. Durations and fees vary by permit type and issuing authority, so confirm the current position before booking anything non-refundable.",
    category: "Tourist",
    relatedCountrySlugs: ["united-arab-emirates"],
    relatedServiceSlugs: ["tourist-visa"],
    relatedGuideSlugs: ["uae-visa-from-india"],
  },
  {
    id: "uae-in-5",
    question: "Does the same UAE entry process apply in Dubai and the other emirates?",
    answer: "Not entirely. The UAE administers visitor entry both federally and at emirate level, and Dubai has its own residency and foreigners affairs authority with its own service pages and fees. Guidance you find may describe a different authority from the one governing your entry point, so check the authority for the emirate you are actually flying into.",
    category: "General",
    relatedCountrySlugs: ["united-arab-emirates"],
    relatedGuideSlugs: ["uae-visa-from-india"],
  },
  {
    id: "uae-in-6",
    question: "Can I leave the airport during a UAE transit stop?",
    answer: "Not automatically. Transiting through a UAE airport is not the same as being permitted to enter the country, and leaving the airport requires appropriate permission for entry. If your itinerary includes a long layover you intend to spend in the city, treat that as an entry question and resolve it before you travel rather than at the airport.",
    category: "General",
    relatedCountrySlugs: ["united-arab-emirates"],
    relatedGuideSlugs: ["uae-visa-from-india"],
  },
  {
    id: "us-in-1",
    question: "Can I still renew my US visa without an interview?",
    answer: "Only within a narrow window. Since 1 October 2025 the interview waiver covers B-1, B-2, B1/B2 and Border Crossing Card renewals made within 12 months of the previous visa expiring, where that visa was issued for full validity and you were at least 18. You must have no unresolved prior refusal and must apply in your country of nationality or residence. A consular officer can still require an interview.",
    category: "Tourist",
    relatedCountrySlugs: ["united-states"],
    relatedGuideSlugs: ["us-visitor-visa-from-india"],
  },
  {
    id: "us-in-2",
    question: "My US visa expired three years ago. Do I qualify for a waiver?",
    answer: "No. The renewal window is 12 months from the expiry of the previous visa. A visa that lapsed three years ago places you outside it, so plan for an in-person interview and build your timeline around appointment availability rather than around a dropbox submission.",
    category: "Tourist",
    relatedCountrySlugs: ["united-states"],
    relatedGuideSlugs: ["us-visitor-visa-from-india"],
  },
  {
    id: "us-in-3",
    question: "How much is the US B1/B2 application fee?",
    answer: "The non-immigrant visa application fee, known as the MRV fee, is USD 185 for a B1/B2. It is paid before your appointment and is not refunded if the application is refused. A separate reciprocity or issuance fee can apply after approval depending on nationality and category, so check the official fee schedule for your total.",
    category: "Tourist",
    relatedCountrySlugs: ["united-states"],
    relatedGuideSlugs: ["us-visitor-visa-from-india"],
  },
  {
    id: "us-in-4",
    question: "How long is the wait for a US visa appointment in India?",
    answer: "Appointment availability changes constantly and differs by consular post and visa category, so any figure quoted in an article will be wrong by the time you read it. The Department of State publishes current wait times by post. Check the post you will apply at on the day you are planning, and build your timeline from that.",
    category: "Tourist",
    relatedCountrySlugs: ["united-states"],
    relatedGuideSlugs: ["us-visitor-visa-from-india"],
  },
  {
    id: "us-in-5",
    question: "Does a previous refusal affect interview waiver eligibility?",
    answer: "Yes. Having never been refused a visa is one of the conditions, unless the refusal was overcome or waived. A prior refusal therefore removes the waiver route as well as affecting the application itself. Declare it either way, because non-disclosure damages credibility far more than the refusal does.",
    category: "Refusals",
    relatedCountrySlugs: ["united-states"],
    relatedServiceSlugs: ["refusal-review"],
    relatedGuideSlugs: ["us-visitor-visa-from-india", "understanding-visa-refusal-reasons"],
  },
  {
    id: "us-in-6",
    question: "How much does the DS-160 matter if I have an interview?",
    answer: "A great deal. The consular officer reads your DS-160 during the interview, so it is the application rather than a preliminary form. Differences between what you wrote and what you say are usually careless rather than dishonest, but they are read as inconsistency. Re-read it before you attend.",
    category: "Interviews",
    relatedCountrySlugs: ["united-states"],
    relatedServiceSlugs: ["interview-preparation"],
    relatedGuideSlugs: ["us-visitor-visa-from-india", "visa-interview-preparation-guide"],
  },
  {
    id: "ca-in-1",
    question: "Can Indian citizens travel to Canada on an eTA instead of a visa?",
    answer: "Not currently. Canada allows citizens of certain visa-required countries to apply for an eTA for air travel, on condition they held a Canadian visitor visa in the past 10 years or hold a valid US non-immigrant visa. India is not among the eligible countries, so Indian citizens generally apply for a Temporary Resident Visa. The eligible list has been extended before, so confirm it on the official page.",
    category: "Tourist",
    relatedCountrySlugs: ["canada"],
    relatedGuideSlugs: ["canada-visitor-visa-from-india"],
  },
  {
    id: "ca-in-2",
    question: "Does holding a US visa help my Canadian application?",
    answer: "Not as a substitute for a visitor visa. A valid US non-immigrant visa is one condition of the eTA route, but that route is only open to citizens of countries on the eligible list, and India is not on it. Your US visa may still be useful supporting evidence of travel history, which is a different thing from an entry permission.",
    category: "Tourist",
    relatedCountrySlugs: ["canada"],
    relatedGuideSlugs: ["canada-visitor-visa-from-india"],
  },
  {
    id: "ca-in-3",
    question: "What does a Canadian visitor visa cost?",
    answer: "The visitor visa fee is CAD 100 per person, with a maximum of CAD 500 for a family of five or more applying at the same time and place. Biometrics add CAD 85 per person, capped at CAD 170 for a family of two or more eligible applicants applying together.",
    category: "Tourist",
    relatedCountrySlugs: ["canada"],
    relatedGuideSlugs: ["canada-visitor-visa-from-india"],
  },
  {
    id: "ca-in-4",
    question: "Do I need to give biometrics again for a second Canadian application?",
    answer: "Usually not. Biometrics given for a Canadian visitor visa, study permit or work permit stay valid for 10 years, and within that period you do not need to give them again for a further visitor visa, work permit or study permit. Check when you last gave them before paying the fee or booking a collection appointment.",
    category: "Documentation",
    relatedCountrySlugs: ["canada"],
    relatedGuideSlugs: ["canada-visitor-visa-from-india"],
  },
  {
    id: "ca-in-5",
    question: "Should my family apply for Canadian visitor visas together?",
    answer: "It is usually cheaper. Family fee maximums apply when a family applies at the same time and place: CAD 500 for the visa where five or more people apply, and CAD 170 for biometrics where two or more eligible people apply. Applying separately out of habit can cost more with no advantage.",
    category: "Family",
    relatedCountrySlugs: ["canada"],
    relatedServiceSlugs: ["family-dependent-visa"],
    relatedGuideSlugs: ["canada-visitor-visa-from-india"],
  },
  {
    id: "ca-in-6",
    question: "Would an eTA cover entering Canada by land from the United States?",
    answer: "No. Even for travellers whose nationality makes them eligible, the eTA covers air travel only. Arriving by car, bus, train or boat, including a cruise ship, requires a visitor visa. If your itinerary includes crossing overland from the US, plan for the visa regardless.",
    category: "Tourist",
    relatedCountrySlugs: ["canada"],
    relatedGuideSlugs: ["canada-visitor-visa-from-india"],
  },
  {
    id: "sg-in-1",
    question: "Can I apply for a Singapore visa myself from India?",
    answer: "No. An entry visa application is submitted on your behalf, not lodged directly by you. The routes are an online submission by a strategic partner or a local contact in Singapore, an application at a Singapore Overseas Mission, or an authorised visa agent. Identifying who will submit for you is the first step, not a detail to sort out later.",
    category: "Tourist",
    relatedCountrySlugs: ["singapore"],
    relatedGuideSlugs: ["singapore-visa-from-india"],
  },
  {
    id: "sg-in-2",
    question: "How much does a Singapore entry visa cost?",
    answer: "A processing fee of SGD 30, paid online by credit or debit card. It is non-refundable, so it is not returned if the application is unsuccessful. Any additional charge you are quoted beyond that belongs to the agent submitting for you, not to the authority.",
    category: "Tourist",
    relatedCountrySlugs: ["singapore"],
    relatedGuideSlugs: ["singapore-visa-from-india"],
  },
  {
    id: "sg-in-3",
    question: "Is the SG Arrival Card a visa?",
    answer: "No, and it is free. The SG Arrival Card is a separate submission and grants no permission to enter. Completing it does nothing about your visa requirement. Sites charging a fee to fill it in for you are not official services, and paying one leaves your actual visa position unchanged.",
    category: "General",
    relatedCountrySlugs: ["singapore"],
    relatedGuideSlugs: ["singapore-visa-from-india"],
  },
  {
    id: "sg-in-4",
    question: "How long does a Singapore visa take to process?",
    answer: "Normally within three working days, excluding the day of submission, though some applications take longer. Apply within the thirty days before your arrival. The window is narrow at both ends, so aim for the middle of it rather than either edge.",
    category: "Tourist",
    relatedCountrySlugs: ["singapore"],
    relatedGuideSlugs: ["singapore-visa-from-india"],
  },
  {
    id: "sg-in-5",
    question: "Does my Singapore visa decide how long I can stay?",
    answer: "No. The entry visa lets you travel to Singapore and present yourself at immigration. The period of stay is decided at the checkpoint. Since March 2022 visitors are notified of their Visit Pass digitally by email, with nothing endorsed in the passport, and that notification states the stay granted and the last day allowed.",
    category: "General",
    relatedCountrySlugs: ["singapore"],
    relatedGuideSlugs: ["singapore-visa-from-india"],
  },
  {
    id: "sg-in-6",
    question: "Do Indian official or diplomatic passport holders need a Singapore visa?",
    answer: "No. The visa requirement applies to ordinary Indian passports; holders of official and diplomatic Indian passports are exempt. Each traveller is assessed on the passport they personally hold, so one family member's exemption does not extend to relatives travelling on ordinary passports.",
    category: "General",
    relatedCountrySlugs: ["singapore"],
    relatedGuideSlugs: ["singapore-visa-from-india"],
  },
  {
    id: "nz-in-1",
    question: "Can Indian passport holders use an NZeTA instead of a visa?",
    answer: "No. The NZeTA is for travellers holding passports from countries on New Zealand's visa waiver list, and India is not on it. Indian passport holders apply for a Visitor Visa. Australian citizens travelling on an Australian passport need neither, which matters if you are travelling with someone who holds one.",
    category: "Tourist",
    relatedCountrySlugs: ["new-zealand"],
    relatedGuideSlugs: ["new-zealand-visitor-visa-from-india"],
  },
  {
    id: "nz-in-2",
    question: "What does a New Zealand visitor visa cost from India?",
    answer: "The Visitor Visa starts from NZD 441, and most visitors also pay the International Visitor Conservation and Tourism Levy of NZD 100 when they apply. Budget both together. Some categories are exempt from the levy, including Business Visitor Visa and APEC business travel card holders, so check whether yours is before assuming it applies.",
    category: "Tourist",
    relatedCountrySlugs: ["new-zealand"],
    relatedGuideSlugs: ["new-zealand-visitor-visa-from-india"],
  },
  {
    id: "nz-in-3",
    question: "Is the New Zealand visitor levy refunded if my application is declined?",
    answer: "No. Immigration New Zealand states that the levy is not refunded even where an application is declined. That makes a weak application more expensive here than in most places, and it is a strong argument for getting the file right before submitting rather than treating a first attempt as a trial run.",
    category: "Tourist",
    relatedCountrySlugs: ["new-zealand"],
    relatedGuideSlugs: ["new-zealand-visitor-visa-from-india"],
  },
  {
    id: "nz-in-4",
    question: "How long can I stay in New Zealand on a visitor visa?",
    answer: "On a multiple-entry visa, up to a total of six months in each twelve-month period. On a single-entry visa, up to nine months within an eighteen-month period. The multiple-entry figure is cumulative rather than per visit, so leaving and returning does not reset it. Add up any time already spent before planning a second trip.",
    category: "Tourist",
    relatedCountrySlugs: ["new-zealand"],
    relatedGuideSlugs: ["new-zealand-visitor-visa-from-india"],
  },
  {
    id: "nz-in-5",
    question: "Can I work remotely from New Zealand on a visitor visa?",
    answer: "New Zealand allows working remotely for a business overseas while visiting, which many countries do not. It is not permission to take up work in New Zealand. Describe it precisely: a visit during which you keep working for your employer at home reads very differently from a trip described loosely as a work visit.",
    category: "Work",
    relatedCountrySlugs: ["new-zealand"],
    relatedGuideSlugs: ["new-zealand-visitor-visa-from-india"],
  },
  {
    id: "jp-in-1",
    question: "Does Japan still put a visa sticker in the passport for Indian applicants?",
    answer: "No. Since the eVisa system started in India on 1 April 2024, approved applicants receive a visa issuance notice in electronic form rather than a sticker. Finding nothing in your passport does not mean the application failed. You will need to produce the electronic notice at the airport instead.",
    category: "Tourist",
    relatedCountrySlugs: ["japan"],
    relatedGuideSlugs: ["japan-visa-from-india"],
  },
  {
    id: "jp-in-2",
    question: "How do I show a Japan eVisa at the airport?",
    answer: "On a mobile device, and displaying it requires internet access. That makes a charged phone and a working connection part of your travel documents in practice. Plan for how you will get online at the airport, particularly if you are connecting through a country where your Indian SIM will not roam.",
    category: "Tourist",
    relatedCountrySlugs: ["japan"],
    relatedGuideSlugs: ["japan-visa-from-india"],
  },
  {
    id: "jp-in-3",
    question: "How much is a Japanese visa for Indian nationals?",
    answer: "From 1 July 2026 the fee for Indian nationals is INR 500, for single or multiple entry, with the VFS Global service fee charged in addition. This is low by international standards, so if an intermediary is quoting many multiples of it, you are paying for their handling rather than for the visa itself.",
    category: "Tourist",
    relatedCountrySlugs: ["japan"],
    relatedGuideSlugs: ["japan-visa-from-india"],
  },
  {
    id: "jp-in-4",
    question: "What does the Japan eVisa cover?",
    answer: "Single-entry short-term stays for tourism, of up to 90 days. It is open to Indian nationals and to foreign nationals resident in India. It is not a work or study permission and is not a route to a longer stay extended after arrival. If your purpose is different, the eVisa is the wrong instrument.",
    category: "Tourist",
    relatedCountrySlugs: ["japan"],
    relatedGuideSlugs: ["japan-visa-from-india"],
  },
  {
    id: "jp-in-5",
    question: "How much does the itinerary matter for a Japanese visa?",
    answer: "More than for most destinations. A Japanese application is read for whether the trip described actually hangs together, so a schedule with cities in an impossible order or hotel dates that contradict the flights undermines an otherwise sound application. Build the itinerary from the bookings you hold rather than inventing one to fill the field.",
    category: "Documentation",
    relatedCountrySlugs: ["japan"],
    relatedServiceSlugs: ["documentation-review"],
    relatedGuideSlugs: ["japan-visa-from-india"],
  },
  {
    id: "kr-in-1",
    question: "Can Indian passport holders apply for K-ETA?",
    answer: "No. K-ETA is for nationals of countries that can enter Korea without a visa, and Indian passport holders are not in that group. The route is a short-term visitor visa instead. Applying for a K-ETA, or paying a site to apply for one, does nothing about the requirement you actually have.",
    category: "Tourist",
    relatedCountrySlugs: ["south-korea"],
    relatedGuideSlugs: ["south-korea-visa-from-india"],
  },
  {
    id: "kr-in-2",
    question: "What does a South Korean tourist visa cost from India?",
    answer: "The basic rate for a single-entry C-3-9 tourist visa, permitting a stay of no more than 90 days, is USD 40. Korean missions publish these as basic rates and note that different fees apply to some countries, so confirm the figure with the mission handling your application. The visa application centre charges its own service fee on top.",
    category: "Tourist",
    relatedCountrySlugs: ["south-korea"],
    relatedGuideSlugs: ["south-korea-visa-from-india"],
  },
  {
    id: "kr-in-3",
    question: "Where do I submit a Korean visa application in India?",
    answer: "Through the Korea Visa Application Centre, which the Embassy operates in partnership with VFS Global. The Centre handles the whole process rather than only collection: submission, processing, issuance, collection and counselling. Korea maintains an Embassy in New Delhi and Consulates General in Mumbai and Chennai, and which one is competent depends on where you live.",
    category: "Tourist",
    relatedCountrySlugs: ["south-korea"],
    relatedGuideSlugs: ["south-korea-visa-from-india"],
  },
  {
    id: "kr-in-4",
    question: "Why do sites offer to file a K-ETA for me if I cannot use one?",
    answer: "Because the scheme is heavily publicised and few articles state who it is actually for. The official K-ETA service says applications are made only through its own website or app, and warns against third-party agencies charging inflated fees. A large quote for a Korean travel authorisation is a signal to stop, especially when the product may not apply to your passport.",
    category: "General",
    relatedCountrySlugs: ["south-korea"],
    relatedGuideSlugs: ["south-korea-visa-from-india"],
  },
  {
    id: "kr-in-5",
    question: "Which short-term category should I apply under for Korea?",
    answer: "C-3 covers several short-term purposes and C-3-9 is the tourist one. Choose the category that describes your actual trip. Applying under tourism because it looks simplest, when the real purpose is a conference or business meetings, creates a mismatch between what you asked for and what your documents show.",
    category: "Business",
    relatedCountrySlugs: ["south-korea"],
    relatedServiceSlugs: ["business-visa"],
    relatedGuideSlugs: ["south-korea-visa-from-india"],
  },
];
